[build]
  command = "cd Frontend && npm ci && npm run build"
  publish = "Frontend/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
directory = "disabled"