# Generated by Django 5.2.12 on 2026-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
