# Generated by Django 5.2.10 on 2026-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_audiofiles_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='model_name',
            field=models.CharField(default='base', help_text='Whisper model used for transcription', max_length=50),
        ),
        migrations.AddField(
            model_name='transcription',
            name='reference_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='wer_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
