# Generated by Django 5.2.10 on 2026-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_audiofiles_file_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationresults',
            old_name='accuracy_score',
            new_name='wer',
        ),
        migrations.RemoveField(
            model_name='evaluationresults',
            name='error_rate',
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='cer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='deletions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='dialect',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='insertions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='mer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='substitutions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='wil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='wip',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
