# Generated by Django 5.2.10 on 2026-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_rename_accuracy_score_evaluationresults_wer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresults',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
