# Generated by Django 5.2.10 on 2026-04-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0009_evaluationresults_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresults',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
