# Generated by Django 5.2.12 on 2026-05-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0011_evaluationreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationReport',
        ),
    ]
