# Generated by Django 5.2.12 on 2026-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0012_delete_evaluationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresults',
            name='alignment',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
