# Generated by Django 5.2.12 on 2026-05-10 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0013_evaluationresults_alignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationresults',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='evaluationresults',
            name='evaluation_date',
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
